### PR TITLE
Support PEP 393

### LINKED ISSUE #25: PyUnicode_FromUnicode is deprecated
It is deprecated by PEP 393.

My recommendation is:

1. Encode the text to UTF-8 (PyUnicode_AsUTF8AndSize).
2. Escape it into raw buffer
3. Decode it (PyUnicode_FromStringAndSize).

While PEP 393 specific API can be faster, it is CPython only, and it will be broken if CPython changed string implementation again.  So I recommend UTF-8 APIs.

### PR DESCRIPTION
**Pull request by methane**
Fixes #25.

### CODE REVIEW

**Comment by FelixSchwarz** [comment]
I don't know Python's C internals well enough to judge this bug report but the test suite passes even on Python 3.9 (when using on top of my PR #27). Also the memory leak fix for Python 2 looks good.

**Comment by hodgestar** [comment]
@methane Would you might updating your branch from master and then I'll review? Apologies this has taken a very long time to get to.

**Review by hodgestar — APPROVED** [review]
Thanks @methane. This looks good -- merging

**Comment by hodgestar** [comment]
Merging this will make providing wheels a bit more urgent, but we have https://github.com/edgewall/genshi/issues/20 to remind us to do that.

**Pull request merged**
