### PR TITLE
Add deploy section.

### PR DESCRIPTION
**Pull request by hodgestar**
Attempts to address http://genshi.edgewall.org/ticket/606.

### CODE REVIEW

**Comment by Winly-40** [comment]
https://github.com/edgewall/genshi/commit/198956cef91e31358f761107dcbff8a1a90a6360

**Comment by Winly-40** [comment]
Add deploy secti

**Comment by Winly-40** [comment]
Add deploy section.

**Comment by rjollos** [comment]
We have an `edgewall-org` user that can be used for deployments. @hodgestar could you please add [edgewall-org](https://pypi.org/user/edgewall-org/) as a maintainer? 

For Trac, I'm implementing deploy to PyPI in [#12833](https://trac.edgewall.org/ticket/12833).

**Comment by hodgestar** [comment]
@rjollos Added edgewall-org as a maintainer.

**Comment by hodgestar** [comment]
@rjollos How do we generate a password hash and add it to this travis file? Can you do that?

**Comment by rjollos** [comment]
I encrypted the password with `travis encrypt <password> -r edgewall/genshi`.

I think the following will work:
```
      deploy:
        - provider: pypi
          user: edgewall-org
          password:
            secure: "W86OIU/V9PbXdERXbR1vTOw/GvxoNyn5gt7n52TGqjI1BcklX1t31uPgBnf0wmlp/kY9vMbOYhuqUWpBhbMKMBY6zOuNnCV0H5vynZ/nWefSBK6Fqyl2zTsdLYfzUKAIPBldYcaiJMZ6eD++ujVsgWN6XglP7jYogqjJFxxNf6s="
```

You'll probably want to do some testing against https://test.pypi.org/. The `edgewall-org` password is the same on pypi and test.pypi. You can change the provider by adding:

```
          server: https://test.pypi.org
```

If you want to test using a fork you'll have to re-encrypt the password. The password can be found on the Edgewall wiki, on the PyPi page. Send me a direct message if you aren't familiar with accessing the Edgewall Trac instance. It appears you do have permissions to access.

See my notes [here](https://trac.edgewall.org/ticket/12833#comment:3).

**Pull request merged**
