### PR TITLE
 Do not merge sub directives if they have not been changed 

### LINKED ISSUE #48: Translator filter merge sub-directives
I have wrote a test that shows the problem: https://github.com/cedk/genshi/commit/53f60233156b87190f03b7dca3f59cd6acaba56b

### PR DESCRIPTION
**Pull request by cedk**
When extracting new directives only new sub directives must be merged in
the parent sub directive.

Fixes #48

### CODE REVIEW

**Comment by FelixSchwarz** [comment]
Thank you very much for your contribution. As the test suite is happy I guess we can merge that. However the new condition seems to be pretty complex and I can't figure out what it actually does. Any chance we can ease understanding that piece of code with some local variables (= good naming) or a comment?

**Comment by cedk** [comment]
Indeed it is testing that the new directives have been added to the substream by the extra directive.
I do not know how you are naming usually the content of a substream?

**Comment by cedk** [comment]
@FelixSchwarz Is the comment enough? It will be great if we could have soon a release with this fix.

**Comment by FelixSchwarz** [comment]
@cedk I guess the comment is ok - the code itself is complex but that's the way it is.

Unfortunately I have almost zero free time in December so @hodgestar could handle/merge this issue?

**Comment by zipus** [comment]
> Unfortunately I have almost zero free time in December so @hodgestar could handle/merge this issue?
Could anyone find some time to merge?

**Comment by cedk** [comment]
It is too bad this did not reach 0.7.6. Is there something I can do to not miss the next release?

**Comment by hodgestar** [comment]
@cedk I'm sorry this didn't get merged, but I didn't want to delay the release. Now that I've migrated the release process to Github Actions, I think the solution is to just to another release as soon as the current PRs are dealt with.

**Review by hodgestar — APPROVED** [review]

**Pull request merged**
